version: "2"

linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    #- forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Xelon-AG/terraform-provider-xelon
        - github.com/Xelon-AG/xelon-sdk-go

output:
  formats:
    tab:
      path: stdout
      colors: false
