name: "🚀 Feature request"
description: "Suggest a new feature or other enhancement"
labels: [ "kind/enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue. Please note that we try to keep the
        Terraform issue tracker reserved for bug reports and feature requests.
        For general usage questions, please see: https://www.terraform.io/community.html.

  - type: textarea
    attributes:
      label: Current Terraform and Xelon provider version
      description: |
        Run `terraform -v` to show the version, and include the output below.
        This will record which version was current at the time of your feature request,
        to help manage the request backlog.

        If you're not using the latest version, please check to see if something related
        to your request has already been implemented in a later version.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Provide a quick (or expanded!) overview of the proposed change.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use cases
      description: |
        In order to properly evaluate a feature request, it is necessary to understand
        the use-cases for it. Please describe below the _end goal_ you are trying
        to achieve that has led you to request this feature.

        Please keep this section focused on the problem and not on the suggested
        solution. We'll get to that in a moment, below!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Potential Terraform configuration
      description: Show how you think this should work and interact.
      value: |
        ```hcl
        ...
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: References
      description: |
        Are there any other GitHub issues, whether open or closed, that are related to
        the problem you've described above or to the suggested solution? If so, please
        create a list below that mentions each of them.
    validations:
      required: false
