name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install tools
        run: make tools

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Generate changelog
        run: |
          git-chglog --config .github/changelog/config.yaml --output .release/DRAFT.md $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --config .github/goreleaser.yaml --rm-dist --release-notes=.release/DRAFT.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
